### ISSUE TITLE
Backport

### ISSUE THREAD

**Issue by Mozork01** [GreenhouseTeam/rapscallions-and-rockhoppers#7]
Hey
Backport Fabric 1.20.1 ?

**Comment by ChrysanthCow** [comment]
Hi, I'd really prefer not to.

And even if I wanted to, I'm already pretty burnt out when it comes to developing this mod right now.

**Comment by ChrysanthCow** [comment]
I changed my mind, maybe when the mod is stable I'll work on this.

**Comment by Mozork01** [comment]
Good Luck 💪

**Comment by ChrysanthCow** [comment]
Not happening due to rewrites to the codebase for 1.21.
