### ISSUE TITLE
Forge 1.20.1

### ISSUE THREAD

**Issue by MartinRakus** [GreenhouseTeam/rapscallions-and-rockhoppers#8]
Any plans of adding a Forge version? Would love to see those little penguins on my 1.20.1 Forge server.

**Comment by ChrysanthCow** [comment]
Technically a duplicate of #7. I'd want to fix issues with the penguin ai first before I consider backporting.

**Comment by MartinRakus** [comment]
The backport to version 1.20.1 is not the important part, main part of my question was Forge support, but I understand.

**Comment by ChrysanthCow** [comment]
Not happening due to rewrites to the codebase for 1.21.
